### ISSUE TITLE
how to create new scene

### ISSUE THREAD

**Issue by WYJBIT** [SJTU-ViSYS-team/VisFly#12]
Thanks for your great contribution to the field of drone simulation !!!
I have read the official documentation of habitat-sim: https://aihabitat.org/docs/habitat-sim/attributesJSON.html and found that the way to create a new scene is to manually modify the JSON file. Is this the only way to create a scene? And how to simply visualize a new scene?

**Comment by Fanxing-LI** [comment]
For me, I am used to write a simple script to generate scenes. It is too slow to manually modify JSON one by one. 
Is this the only way to create a scene? Yes.
And how to simply visualize a new scene? Use habitat-sim built-in file viewer.py.

**Comment by WYJBIT** [comment]
Thank you for your reply!
