### ISSUE TITLE
Import issue with relative/absolute path

### ISSUE THREAD

**Issue by cmakelabs** [SJTU-ViSYS-team/VisFly#3]
Thanks for VisFly! 
While trying it out, I have encountered the following issue
```

(VisFly) noetic@noetic:~/vsim/VisFly$ python3 examples/cluttered_flight/rl.py -t 1
Traceback (most recent call last):
  File "/home/noetic/vsim/VisFly/examples/cluttered_flight/rl.py", line 14, in <module>
    from envs.NavigationEnv import NavigationEnv
  File "/home/noetic/vsim/VisFly/envs/NavigationEnv.py", line 2, in <module>
    from .droneGymEnv import DroneGymEnvsBase
  File "/home/noetic/vsim/VisFly/envs/droneGymEnv.py", line 4, in <module>
    from .droneEnv import DroneEnvsBase
  File "/home/noetic/vsim/VisFly/envs/droneEnv.py", line 2, in <module>
    from .dynamics import Dynamics
  File "/home/noetic/vsim/VisFly/envs/dynamics.py", line 9, in <module>
    from ..utils.maths import Quaternion, Integrator, cross
ImportError: attempted relative import beyond top-level package

```

I assume, it is due to having the relative import is relative to your current working directory, not the file where the import happens. I would be grateful if you could tell how to overcome this issue elegantly, without modifying the manually every script.

**Comment by Fanxing-LI** [comment]
Sorry for that. VisFly should have been an individual module and I add relative imports while handling another research. 
Your can solve it by moving examples out of VisFly. for example:
----------------------------------
root
├─VisFly/
├─examples/
...
-----------------------------------

**Comment by Fanxing-LI** [comment]
Sorry for that, VisFly should have been a module to be used for other projects. You can move examples out of VisFly to fix this problem. We have updated the repository and the Section `Quick Start`  to explain it more clearly.

**Comment by Fanxing-LI** [comment]
It seems that you need to pull the latest code, the beginning section inlcuding line 10 in latest version is :
```
#!/usr/bin/env python3

import sys
import os
import numpy as np
import torch
import time

sys.path.append(os.getcwd())
from VisFly.utils.policies import extractors
from VisFly.utils.algorithms.ppo import ppo
from VisFly.utils import savers
import torch as th
from VisFly.envs.NavigationEnv import NavigationEnv
from VisFly.utils.launcher import rl_parser, training_params
from VisFly.utils.type import Uniform
```
If you meet any other problem, please inform me of it.

**Comment by gaojunjie1999** [comment]
I came into the same error, I solved it by deleting those non-existing lines from the json file. It seems these files are missing from the provided spy_datasets.

**Comment by gaojunjie1999** [comment]
my spy_datasets.scene_dataset_conmfig.json is like:
{
    "stages": {
        "paths": {
            ".json": [
                "configs/stages"
            ]
        }
    },
    "objects": {
        "paths": {
            ".json": [
                "configs/objects",
                "configs/objects2",
                "configs/agents",
                "configs/self_define_objects"
            ]
        }
    },
    "articulated_objects": {
        "paths": {
            ".urdf": [
                "urdf/*/",
                "../hab_fetch_1.0/robots/fetch_no_base.urdf"
            ]
        }
    },
    "light_setups": {
        "default_attributes": {
            "positive_intensity_scale": 2.5,
            "negative_intensity_scale": 0.1
        },
        "paths": {
            ".json": [
                "configs/lighting"
            ]
        }
    },
    "scene_instances": {
        "default_attributes": {
            "semantic_scene_instance": "replicaCAD_ssd_map"
        },
        "paths": {
            ".json": [
                "configs/scenes",
                "configs/scenes_selected",
                "configs/garage_empty",
                "configs/garage_simple",
                "configs/garage_test",
                "configs/garage_simple_l",
                "configs/garage_simple_h",
                "configs/garage_simple_l_long",
                "configs/garage_landing",
                "configs/garage_crossing",
                "configs/garage_simple_l_medium"
            ]
        }
    },
    "navmesh_instances": {
        "empty_stage": "navmeshes/empty_stage.navmesh",
        "apt_0": "navmeshes/apt_0.navmesh",
        "apt_1": "navmeshes/apt_1.navmesh",
        "apt_2": "navmeshes/apt_2.navmesh",
        "apt_3": "navmeshes/apt_3.navmesh",
        "apt_4": "navmeshes/apt_4.navmesh",
        "apt_5": "navmeshes/apt_5.navmesh",
        "v3_sc0_staging_00": "navmeshes/v3_sc0_staging_00.navmesh",
        "v3_sc0_staging_01": "navmeshes/v3_sc0_staging_01.navmesh",
        "v3_sc0_staging_02": "navmeshes/v3_sc0_staging_02.navmesh",
        "v3_sc0_staging_03": "navmeshes/v3_sc0_staging_03.navmesh",
        "v3_sc0_staging_04": "navmeshes/v3_sc0_staging_04.navmesh",
        "v3_sc0_staging_05": "navmeshes/v3_sc0_staging_05.navmesh",
        "v3_sc0_staging_06": "navmeshes/v3_sc0_staging_06.navmesh",
        "v3_sc0_staging_07": "navmeshes/v3_sc0_staging_07.navmesh",
        "v3_sc0_staging_08": "navmeshes/v3_sc0_staging_08.navmesh",
        "v3_sc0_staging_09": "navmeshes/v3_sc0_staging_09.navmesh",
        "v3_sc0_staging_10": "navmeshes/v3_sc0_staging_10.navmesh",
        "v3_sc0_staging_11": "navmeshes/v3_sc0_staging_11.navmesh",
        "v3_sc0_staging_12": "navmeshes/v3_sc0_staging_12.navmesh",
        "v3_sc0_staging_13": "navmeshes/v3_sc0_staging_13.navmesh",
        "v3_sc0_staging_14": "navmeshes/v3_sc0_staging_14.navmesh",
        "v3_sc0_staging_15": "navmeshes/v3_sc0_staging_15.navmesh",
        "v3_sc0_staging_16": "navmeshes/v3_sc0_staging_16.navmesh",
        "v3_sc0_staging_17": "navmeshes/v3_sc0_staging_17.navmesh",
        "v3_sc0_staging_18": "navmeshes/v3_sc0_staging_18.navmesh",
        "v3_sc0_staging_19": "navmeshes/v3_sc0_staging_19.navmesh",
        "v3_sc0_staging_20": "navmeshes/v3_sc0_staging_20.navmesh",
        "v3_sc1_staging_00": "navmeshes/v3_sc1_staging_00.navmesh",
        "v3_sc1_staging_01": "navmeshes/v3_sc1_staging_01.navmesh",
        "v3_sc1_staging_02": "navmeshes/v3_sc1_staging_02.navmesh",
        "v3_sc1_staging_03": "navmeshes/v3_sc1_staging_03.navmesh",
        "v3_sc1_staging_04": "navmeshes/v3_sc1_staging_04.navmesh",
        "v3_sc1_staging_05": "navmeshes/v3_sc1_staging_05.navmesh",
        "v3_sc1_staging_06": "navmeshes/v3_sc1_staging_06.navmesh",
        "v3_sc1_staging_07": "navmeshes/v3_sc1_staging_07.navmesh",
        "v3_sc1_staging_08": "navmeshes/v3_sc1_staging_08.navmesh",
        "v3_sc1_staging_09": "navmeshes/v3_sc1_staging_09.navmesh",
        "v3_sc1_staging_10": "navmeshes/v3_sc1_staging_10.navmesh",
        "v3_sc1_staging_11": "navmeshes/v3_sc1_staging_11.navmesh",
        "v3_sc1_staging_12": "navmeshes/v3_sc1_staging_12.navmesh",
        "v3_sc1_staging_13": "navmeshes/v3_sc1_staging_13.navmesh",
        "v3_sc1_staging_14": "navmeshes/v3_sc1_staging_14.navmesh",
        "v3_sc1_staging_15": "navmeshes/v3_sc1_staging_15.navmesh",
        "v3_sc1_staging_16": "navmeshes/v3_sc1_staging_16.navmesh",
        "v3_sc1_staging_17": "navmeshes/v3_sc1_staging_17.navmesh",
        "v3_sc1_staging_18": "navmeshes/v3_sc1_staging_18.navmesh",
        "v3_sc1_staging_19": "navmeshes/v3_sc1_staging_19.navmesh",
        "v3_sc1_staging_20": "navmeshes/v3_sc1_staging_20.navmesh",
        "v3_sc2_staging_00": "navmeshes/v3_sc2_staging_00.navmesh",
        "v3_sc2_staging_01": "navmeshes/v3_sc2_staging_01.navmesh",
        "v3_sc2_staging_02": "navmeshes/v3_sc2_staging_02.navmesh",
        "v3_sc2_staging_03": "navmeshes/v3_sc2_staging_03.navmesh",
        "v3_sc2_staging_04": "navmeshes/v3_sc2_staging_04.navmesh",
        "v3_sc2_staging_05": "navmeshes/v3_sc2_staging_05.navmesh",
        "v3_sc2_staging_06": "navmeshes/v3_sc2_staging_06.navmesh",
        "v3_sc2_staging_07": "navmeshes/v3_sc2_staging_07.navmesh",
        "v3_sc2_staging_08": "navmeshes/v3_sc2_staging_08.navmesh",
        "v3_sc2_staging_09": "navmeshes/v3_sc2_staging_09.navmesh",
        "v3_sc2_staging_10": "navmeshes/v3_sc2_staging_10.navmesh",
        "v3_sc2_staging_11": "navmeshes/v3_sc2_staging_11.navmesh",
        "v3_sc2_staging_12": "navmeshes/v3_sc2_staging_12.navmesh",
        "v3_sc2_staging_13": "navmeshes/v3_sc2_staging_13.navmesh",
        "v3_sc2_staging_14": "navmeshes/v3_sc2_staging_14.navmesh",
        "v3_sc2_staging_15": "navmeshes/v3_sc2_staging_15.navmesh",
        "v3_sc2_staging_16": "navmeshes/v3_sc2_staging_16.navmesh",
        "v3_sc2_staging_17": "navmeshes/v3_sc2_staging_17.navmesh",
        "v3_sc2_staging_18": "navmeshes/v3_sc2_staging_18.navmesh",
        "v3_sc2_staging_19": "navmeshes/v3_sc2_staging_19.navmesh",
        "v3_sc2_staging_20": "navmeshes/v3_sc2_staging_20.navmesh",
        "v3_sc3_staging_00": "navmeshes/v3_sc3_staging_00.navmesh",
        "v3_sc3_staging_01": "navmeshes/v3_sc3_staging_01.navmesh",
        "v3_sc3_staging_02": "navmeshes/v3_sc3_staging_02.navmesh",
        "v3_sc3_staging_03": "navmeshes/v3_sc3_staging_03.navmesh",
        "v3_sc3_staging_04": "navmeshes/v3_sc3_staging_04.navmesh",
        "v3_sc3_staging_05": "navmeshes/v3_sc3_staging_05.navmesh",
        "v3_sc3_staging_06": "navmeshes/v3_sc3_staging_06.navmesh",
        "v3_sc3_staging_07": "navmeshes/v3_sc3_staging_07.navmesh",
        "v3_sc3_staging_08": "navmeshes/v3_sc3_staging_08.navmesh",
        "v3_sc3_staging_09": "navmeshes/v3_sc3_staging_09.navmesh",
        "v3_sc3_staging_10": "navmeshes/v3_sc3_staging_10.navmesh",
        "v3_sc3_staging_11": "navmeshes/v3_sc3_staging_11.navmesh",
        "v3_sc3_staging_12": "navmeshes/v3_sc3_staging_12.navmesh",
        "v3_sc3_staging_13": "navmeshes/v3_sc3_staging_13.navmesh",
        "v3_sc3_staging_14": "navmeshes/v3_sc3_staging_14.navmesh",
        "v3_sc3_staging_15": "navmeshes/v3_sc3_staging_15.navmesh",
        "v3_sc3_staging_16": "navmeshes/v3_sc3_staging_16.navmesh",
        "v3_sc3_staging_17": "navmeshes/v3_sc3_staging_17.navmesh",
        "v3_sc3_staging_18": "navmeshes/v3_sc3_staging_18.navmesh",
        "v3_sc3_staging_19": "navmeshes/v3_sc3_staging_19.navmesh",
        "v3_sc3_staging_20": "navmeshes/v3_sc3_staging_20.navmesh"
    },
    "semantic_scene_descriptor_instances": {
        "replicaCAD_ssd_map": "configs/ssd/replicaCAD_semantic_lexicon.json"
    }
}

I deleted several lines, since the spy data I downloaded does not have files like v3_sc4*

**Comment by gaojunjie1999** [comment]
I don't think rebuilding is necessary. Maybe you can check your DJI_Mavic_Mini_2.glb file.

**Comment by Fanxing-LI** [comment]
Sorry for reply late because of national vacation. Obviously it is a path problem. In my test , I pause the program at line 722 where your code raise the error.

In my code, the path is as follows:

```self.render_settings["object_path"]
PyDev console: starting.
'/home/lfx-desktop/test/VisFly_root/VisFly/utils/../datasets/spy_datasets/configs/agents/DJI_Mavic_Mini_2.object_config.json'
```

In your code, it is 
```
'/home/noetic/vsim/VisFly/utils/../datasets/spy_datasets/configs/agents/../../agents/DJI_Mavic_Mini_2.glb'
```

Probably you change the source code, please make sure the path is right. Or you can directly reset the current branch to last version.

Besides, the program should be run in the project workspace, not VisFly workspace. please examine it.

**Comment by Fanxing-LI** [comment]
Can you add a breakpoint at line 219 to examine varaible `self._object_path`?, 
In my code it is `self._object_path = root_addr+"datasets/spy_datasets/configs/agents/DJI_Mavic_Mini_2.object_config.json"`. And print `self._object_path`, it shows `'/home/lfx-desktop/test/VisFly_root/VisFly/utils/../datasets/spy_datasets/configs/agents/DJI_Mavic_Mini_2.object_config.json'`.

In your code, the path `'/home/noetic/vsim/VisFly_root/VisFly/utils/../datasets/spy_datasets/configs/agents/../../agents/DJI_Mavic_Mini_2.glb'' includes extra `../../agents/`.

**Comment by Fanxing-LI** [comment]
How about trying to use another model  to represent drone?

In line 219, replace `self._object_path = root_addr+"datasets/spy_datasets/configs/agents/DJI_Mavic_Mini_2.object_config.json"` with `self._object_path = root_addr+"datasets/spy_datasets/configs/objects/frl_apartment_basket.object_config.json"` (or any other in datasets/configs/objects/ folder).

**Comment by Fanxing-LI** [comment]
Oh I know something about it which may be helpful. Habitat-sim reads configuration files `datasets/configs/objects/xxx.json` to load scenes or objects. For example, inside the `datasets/configs/objects/frl_apartment_basket.object_config.json` file, it includes the path of source 3D model file `../../objects/frl_apartment_basket.glb`. Habitatsim is guided to find the source 3D file in `/../../objects/frl_apartment_basket.glb'`. 

So you could examine this file `/home/noetic/vsim/VisFly_root/VisFly/datasets/spy_datasets/objects/frl_apartment_basket.glb` for whether exists or not.

**Comment by Fanxing-LI** [comment]
Oh, I think it is the point, probably because you didnt download the datasets properly. It should be a 3D model file, not content. Maybe try to download it again at https://huggingface.co/datasets/LiFanxing/VisFly-datasets.
