### ISSUE TITLE
Check which physics is used

### ISSUE THREAD

**Issue by cmakelabs** [SJTU-ViSYS-team/VisFly#4]
Thank you for the impressive work, I would like to know if there is a way to check what physics engine is being used. I have installed `habitat-sim` with the flag for `CUDA`, but without specifying the flag for `Bullet`, as the following:

`python setup.py install --with-cuda `

However, I have noticed that Bullet got installed automatically, which is fine, but I am mostly interested in using the self-defined physics as mentioned in Table-1 of [VisFly paper](https://arxiv.org/pdf/2407.14783). Could you please tell me if I am now using the custom physics or `Bullet`? Is there a way to figure out what physics is being used?

**Comment by Fanxing-LI** [comment]
Sorry for reply late bacause of National vacation. This simulator always uses custom physics not built-in bullet. Habitat-sim is rarely considered as a fast rendering engine. If you are interested in how dynamics works, maybe you can add breakpoint in `step` function in dynamics.py file, it will helps you to learn it better.
